Hcmpre 874: Beneficiary Type Enum added
egovernments/health-campaign-services pull request #1033
Opened 2024-10-24 04:54 UTC by yashita-egov

Beneficiary Type Enum added and project type from mdms to project additional details (for beneficiary validation)

2024-11-18 05:12 UTC, naveen-egov approved these changes

2024-12-23 05:37 UTC, kavi-egov requested changes

2024-12-23 05:37 UTC, kavi-egov commented on health-services/project/pom.xml
> +            <version>1.0.24-DEV</version>
should be dev-snapshot

2024-12-23 05:37 UTC, kavi-egov commented on health-services/project/pom.xml
> +            <version>1.0.0-SNAPSHOT</version>
These are removed fom our Dev branch already, take help from Shubang and remove it

2024-12-23 05:37 UTC, kavi-egov commented on health-services/libraries/health-services-models/src/main/java/org/egov/common/models/project/BeneficiaryType.java
> +				if(String.valueOf(a.value).equals(text)){
should be equal ignore case

2024-12-23 05:37 UTC, kavi-egov commented on health-services/project/src/main/java/org/egov/project/validator/beneficiary/BeneficiaryValidator.java
> +    private List<ProjectType> getProjectType(List<Project> existingProjects) {
separate this out as another PR, need not be part of beneficiary type changes

2025-01-03 08:26 UTC, kavi-egov approved these changes

2025-01-03 08:26 UTC, merged