Changing datatype of value
egovernments/health-campaign-services pull request #1063
Opened 2024-11-06 08:31 UTC by tanishi-egov

2024-11-06 08:37 UTC, Priyanka-eGov requested changes

2024-11-06 08:37 UTC, Priyanka-eGov commented on health-services/census-service/src/main/resources/db/migration/main/V20241105152700__census_additional_field_create_ddl.sql
> +  "value"                       numeric(12,2) NOT NULL,
you cannot edit an alreayd existing migrtaion file that has been run.

2024-11-07 07:17 UTC, Priyanka-eGov approved these changes

2024-11-07 07:19 UTC, shashwat-egov approved these changes

2024-11-07 07:19 UTC, merged