PR to develop branch for Microplanning v0.1 (changes in plan-service, resource-generator service and census service)
egovernments/health-campaign-services pull request #1176
Opened 2024-11-26 09:56 UTC by Priyanka-eGov

2024-11-26 10:48 UTC, Priyanka-eGov commented
@CodeRabbit please generate a summary and list the key features in this PR.

2024-12-04 09:09 UTC, sathishp-eGov commented
@coderabbitai review

2024-12-12 07:24 UTC, kavi-egov requested changes

2024-12-12 07:37 UTC, kavi-egov approved these changes

2024-12-12 07:37 UTC, kavi-egov commented on health-services/census-service/src/main/java/digit/repository/rowmapper/StatusCountRowMapper.java
> +        Map<String, Integer> statusCountMap = new HashMap<>();
There is a method in jdbc itself that will give you the map, we don't need this

2024-12-12 07:37 UTC, kavi-egov commented on health-services/census-service/src/main/java/digit/service/CensusService.java
> +        timeframeEnrichment.enrichPreviousTimeframe(request);
What is time Frame enrichment, need comments

2024-12-12 07:37 UTC, merged