[hlm-1419]: Stock
egovernments/health-campaign-services pull request #213
Opened 2023-02-10 10:44 UTC by shivab-egov

2023-02-10 11:02 UTC, jayantp-egov requested changes

2023-02-13 07:15 UTC, shivab-egov commented on health-services/stock/src/main/java/org/egov/stock/config/MainConfiguration.java
> +public class MainConfiguration {
resolved

2023-02-13 07:16 UTC, shivab-egov commented on health-services/stock/src/main/java/org/egov/stock/service/StockService.java
> +            validator -> validator.getClass().equals(SproductVaraintIdValidator.class)
resolved

2023-02-13 07:16 UTC, shivab-egov commented on health-services/stock/src/main/java/org/egov/stock/service/StockService.java
> +            return stockRepository.findById(ids, includeDeleted).stream()
resolved

2023-02-13 07:16 UTC, shivab-egov commented on health-services/stock/src/main/java/org/egov/stock/web/models/Stock.java
> +    private String id = null;
resolved

2023-02-13 11:13 UTC, merged