HCMPRE-400 : plan config name - implement fuzzy search
egovernments/health-campaign-services pull request #873
Opened 2024-08-29 11:26 UTC by tanishi-egov

2024-08-30 05:16 UTC, Priyanka-eGov submitted a review, later dismissed

2024-09-13 07:29 UTC, shashwat-egov requested changes

2024-09-13 07:29 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/repository/querybuilder/PlanConfigQueryBuilder.java
> +            preparedStmtList.add(criteria.getName() + '%');
move % string literal to constants file

2024-09-13 08:01 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/repository/querybuilder/PlanConfigQueryBuilder.java
> +            preparedStmtList.add(criteria.getName() + '%');
done

2024-09-13 08:08 UTC, shashwat-egov approved these changes

2024-09-13 08:08 UTC, shashwat-egov commented
There are conflicts in this branch, please resolve

2024-09-13 09:15 UTC, tanishi-egov commented
yes, done.

On Fri, Sep 13, 2024 at 1:38 PM Shashwat Mishra ***@***.***>
wrote:

> There are conflicts in this branch, please resolve
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/egovernments/health-campaign-services/pull/873#issuecomment-2348306538>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BJCDLVGDLGHW6SBOLIPJ4DLZWKMRTAVCNFSM6AAAAABNKGXRRWVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDGNBYGMYDMNJTHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-13 09:21 UTC, Priyanka-eGov approved these changes

2024-09-18 09:27 UTC, shashwat-egov approved these changes

2024-10-04 07:02 UTC, Priyanka-eGov requested changes

2024-10-04 07:02 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/repository/querybuilder/PlanConfigQueryBuilder.java
> +import static digit.config.ServiceConstants.*;
no need to import all the ServiceConstants, just import your constant

2024-10-04 07:09 UTC, Priyanka-eGov approved these changes

2024-10-04 07:11 UTC, merged