HCMPRE-172: Adding vehicle to plan configuration object
egovernments/health-campaign-services pull request #877
Opened 2024-09-02 10:20 UTC by tanishi-egov

2024-09-03 06:02 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/config/ServiceConstants.java
> +    public static final String MDMS = "mdms";
rename it as MDMS_CODE

2024-09-03 06:10 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/config/ServiceConstants.java
> +    public static final String MDMS = "mdms";
okayy

2024-09-03 11:04 UTC, Priyanka-eGov requested changes

2024-09-04 07:02 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        validateVehicleIdsFromAdditionalDetailsAgainstMDMS(request, mdmsV2Data);
done

2024-09-04 07:02 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        validateVehicleIdsFromAdditionalDetailsAgainstMDMS(request, mdmsV2Data);
> Add a comment above defining what it does

added

2024-09-04 08:11 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +                .filter(vehicleId -> !finalVehicleIdsFromMdms.contains(vehicleId))
> instead of filter let the if condition be inside forEach. its more readable

okayy

2024-09-04 08:12 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/util/MdmsV2Util.java
> +        if(mdmsResponseMap == null || ObjectUtils.isEmpty(mdmsResponseMap))
> redundant null check, ObjectUtils checks for null.

okay

2024-09-04 08:25 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/config/ServiceConstants.java
> +    public static final String MDMS_SCHEMA_VEHICLE = "VehicleDetails";
> VEHICLE_DETAILS is the schema name, update the constant key

Okay

2024-09-09 06:36 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        List<String> vehicleIds = extractVehicleIdsFromAdditionalDetails(request.getPlanConfiguration().getAdditionalDetails());
> Put this extractVehicleIdsFromAdditionalDetails into Util class

Done

2024-09-09 06:36 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        String jsonPathForVehicleIds = "$." + MDMS_CODE + DOT_SEPARATOR + GET_ALL_IDS;
> "$." should be added as a constant after PR merge

done

2024-09-09 11:50 UTC, Priyanka-eGov approved these changes

2024-09-09 11:50 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        final String jsonPathForAssumption = JSON_ROOT_PATH + MDMS_PLAN_MODULE_NAME + DOT_SEPARATOR + MDMS_MASTER_ASSUMPTION + "[*].assumptionCategories[*].assumptions[*]";
can we put it into another constant

2024-09-09 11:59 UTC, tanishi-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        final String jsonPathForAssumption = JSON_ROOT_PATH + MDMS_PLAN_MODULE_NAME + DOT_SEPARATOR + MDMS_MASTER_ASSUMPTION + "[*].assumptionCategories[*].assumptions[*]";
> can we put it into another constant

okay

2024-09-13 07:27 UTC, shashwat-egov approved these changes

2024-09-13 07:27 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        Object mdmsV2Data = mdmsV2Util.fetchMdmsV2Data(request.getRequestInfo(),rootTenantId, MDMS_PLAN_MODULE_NAME + DOT_SEPARATOR + MDMS_SCHEMA_VEHICLE_DETAILS);
add space after every comma

2024-09-13 07:27 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        Object mdmsV2Data = mdmsV2Util.fetchMdmsV2Data(request.getRequestInfo(),rootTenantId, MDMS_PLAN_MODULE_NAME + DOT_SEPARATOR + MDMS_SCHEMA_VEHICLE_DETAILS);
Correct format - there should be a lingering space after every comma

2024-09-13 07:27 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/util/ServiceUtil.java
>  public class ServiceUtil {
change the name to CommonUtil instead

2024-09-13 07:27 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +            log.info(jsonPathForVehicleIds);
remove this logging statement, I believe this was used for testing

2024-09-13 07:27 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/validator/PlanConfigurationValidator.java
> +        List<String> vehicleIds = serviceUtil.extractVehicleIdsFromAdditionalDetails(request.getPlanConfiguration().getAdditionalDetails());
rename this variable to vehicleIdsLinkedWithPlanConfig

2024-09-13 07:27 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/util/MdmsV2Util.java
> +            mdmsResponseMap = restTemplate.postForObject(uri.toString(), mdmsV2CriteriaReq, Map.class);
Why is the response being parsed as response map? MDMS v2 search returns a list of MDMS data entries.

2024-09-13 07:28 UTC, shashwat-egov requested changes

2024-09-18 09:32 UTC, shashwat-egov requested changes

2024-09-18 09:32 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/util/MdmsV2Util.java
> +        try{
reformat this piece of code - after try there should be a space then you should put a bracket

2024-09-18 09:32 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/util/MdmsV2Util.java
> +        {
keep formatting consistent everywhere, in this line too after the bracket there should be a space followed by squidly bracket

2024-09-19 10:27 UTC, shashwat-egov approved these changes

2024-09-24 07:04 UTC, merged