HCMPRE-493 Workflow integration changes for plan config
egovernments/health-campaign-services pull request #934
Opened 2024-10-03 09:31 UTC by Priyanka-eGov

2024-10-03 09:48 UTC, Priyanka-eGov commented
@coderabbitai review

2024-10-03 09:57 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +	}
can't edit spellings, they are part of the workflow.

2024-10-03 09:58 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +			return;
added workflow object null check

2024-10-03 10:02 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +		}
done.

2024-10-03 10:03 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +	}
done

2024-10-03 10:04 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/enrichment/EnrichmentService.java
> +
not required.

2024-10-03 10:05 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/repository/rowmapper/PlanConfigRowMapper.java
> +                planConfigEntry.setStatus(rs.getString("plan_configuration_status").toUpperCase());
Refractoring of resource-estimation-service will be take up in another ticket.

2024-10-03 10:07 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/resources/application.properties
> +egov.mdms.search.endpoint=/mdms-v2/v1/_search
not required.

2024-10-03 10:09 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/resources/application.properties
> +
changed

2024-10-03 10:12 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/web/models/PlanConfiguration.java
> +    private Workflow workflow;
added @Valid annotation

2024-10-03 10:31 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +		planConfigurationRequest.getPlanConfiguration().setStatus(processInstanceAfterTransition.getState().getApplicationStatus());
not required the stream() will throw exception when it does not find an element matching businessId.

2024-10-03 11:10 UTC, shashwat-egov requested changes

2024-10-03 11:10 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +		if (planConfigurationRequest.getPlanConfiguration().getWorkflow().getAction() == null) {
Add condition to omit invocation when workflow object is null or empty. Use ObjectUtils.isEmpty() in both the cases.

2024-10-03 11:10 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +		ProcessInstance processInstanceAfterTransition = processInstanceResponse.getProcessInstances().stream()
why is this required? workflow call will guarantee a response back. Use of filter here is unnecessary

2024-10-03 11:10 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +		planConfigurationRequest.getPlanConfiguration().setStatus(processInstanceAfterTransition.getState().getApplicationStatus());
set the workflow status rather than application status here

2024-10-03 11:10 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +				.collect(toList());
remove collect. it is not required. directly invoke toList.

2024-10-03 11:10 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +		List<User> userUuidList = CollectionUtils.isEmpty(workflow.getAssignes())
rename this to userList

2024-10-03 11:10 UTC, shashwat-egov commented on health-services/plan-service/src/main/java/digit/web/models/PlanConfiguration.java
>      @NotNull
since system is enriching this, status should not be having NotNull annotation

2024-10-03 11:23 UTC, Priyanka-eGov commented on health-services/plan-service/src/main/java/digit/service/workflow/WorkflowService.java
> +        this.config = config;
not present in local

2024-10-04 08:20 UTC, shashwat-egov approved these changes

2024-10-04 08:22 UTC, merged