Project Service - Project Staff - CRUD
egovernments/health-campaign-services pull request #98
Opened 2022-12-21 12:09 UTC by jitendrac-egov

Added

Project Staff Creation, Update, Delete and search

Health Common Services added the User Service

2022-12-22 10:34 UTC, jayantp-egov requested changes

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/main/java/org/egov/project/repository/ProjectRepository.java
> +        String query = String.format(
Use cache here

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/main/java/org/egov/project/repository/ProjectRepository.java
> +        } catch (EmptyResultDataAccessException e) {
Remove this exception, refer dev branch product and product variant code

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/main/java/org/egov/project/repository/ProjectStaffRepository.java
> +    private static final String HASH_KEY = "project-staff";
Add new line after every declaration

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/main/java/org/egov/project/repository/ProjectStaffRepository.java
> +        query += " and tenantId=:tenantId ";
Put proper spaces, refer to latest code from dev branch

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/main/java/org/egov/project/repository/ServiceRequestRepository.java
> +import org.springframework.beans.factory.annotation.Qualifier;
Remove this file. Not needed.

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/main/java/org/egov/project/repository/rowmapper/ProjectStaffRowMapper.java
> +                    .additionalFields(objectMapper.readValue(resultSet.getString("additionalDetails"), AdditionalFields.class))
You will have to write some conversion logic(null check) for additionalDetails. Refer to dev branch.

2022-12-22 10:34 UTC, jayantp-egov commented on health-services/project/src/test/java/org/egov/project/repository/ProjectRepositoryTest.java
> +                            "SELECT id FROM project WHERE id IN (:projectIds) AND isDeleted = false fetch first %s rows only",
Correct formatting

2022-12-22 11:54 UTC, jitendrac-egov commented on health-services/project/src/main/java/org/egov/project/repository/ProjectStaffRepository.java
> +    private static final String HASH_KEY = "project-staff";
Added

2022-12-23 05:50 UTC, jayantp-egov approved these changes

2022-12-23 05:50 UTC, jayantp-egov commented on health-services/libraries/health-services-common/src/main/java/org/egov/common/service/UserService.java
> +            log.error("Exception while searching users : " + e.getMessage());
log.error("message", e)

2022-12-23 06:05 UTC, merged